export const LANGUAGES = [
  {value: 'bson', label: 'BSON'},
  {value: 'c', label: 'C'},
  {value: 'csharp', label: 'C#'},
  {value: 'cpp', label: 'C++'},
  {value: 'css', label: 'CSS'},
  {value: 'clojure', label: 'Clojure'},
  {value: 'coffeescript', label: 'CoffeeScript'},
  {value: 'dart', label: 'Dart'},
  {value: 'django', label: 'Django'},
  {value: 'docker', label: 'Docker'},
  {value: 'graphql', label: 'GraphQL'},
  {value: 'ejs', label: 'EJS'},
  {value: 'go', label: 'Go'},
  {value: 'html', label: 'HTML'},
  {value: 'java', label: 'Java'},
  {value: 'json', label: 'JSON'},
  {value: 'jsx', label: 'JSX'},
  {value: 'javascript', label: 'JavaScript'},
  {value: 'kotlin', label: 'Kotlin'},
  {value: 'less', label: 'Less'},
  {value: 'markdown', label: 'Markdown'},
  {value: 'makefile', label: 'Makefile'},
  {value: 'matlab', label: 'MatLab'},
  {value: 'nginx', label: 'NGINX'},
  {value: 'objectivec', label: 'Objective-C'},
  {value: 'perl', label: 'Perl'},
  {value: 'php', label: 'PHP'},
  {value: 'python', label: 'Python'},
  {value: 'ruby', label: 'Ruby'},
  {value: 'rust', label: 'Rust'},
  {value: 'sass', label: 'Sass'},
  {value: 'scss', label: 'SCSS'},
  {value: 'typescript', label: 'TypeScript'},
  {value: 'yaml', label: 'YAML'},
];

export const SEARCHFILTERS = [
  {value: 'title', label: 'Title'},
  {value: 'language', label: 'Language'},
  {value: 'tag', label: 'Tags'},
]